# Generated by Django 4.0.6 on 2023-01-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecas',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pecas',
            name='venda',
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pecas'),
        ),
        migrations.CreateModel(
            name='Venda_pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.IntegerField(verbose_name='desconto')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('pecas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pecas')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='entrada_pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('data', models.DateField(null=True, verbose_name='Data de cadastro')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pecas')),
            ],
        ),
    ]
