# Generated by Django 4.0.6 on 2023-01-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pecas_quantidade_remove_pecas_venda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada_pecas',
            old_name='nome',
            new_name='pecas',
        ),
    ]
