# Generated by Django 4.0.6 on 2023-01-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_entrada_pecas_pecas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='entrada_pecas',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='valor da compra'),
            preserve_default=False,
        ),
    ]
